name: masjidmobile
description: Mosque info application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.17.0
  freezed_annotation: ^0.14.3
  hooks_riverpod: ^0.14.0+4
  json_serializable: ^5.0.0
  retrofit: ^2.0.1
  shared_preferences: ^2.0.7

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  retrofit_generator: ^2.0.1+1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: DMSans
      fonts:
        - asset: assets/fonts/dmsans/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/dmsans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dmsans/DMSans-Bold.ttf
          weight: 700
    - family: MuseoModerno
      fonts:
        - asset: assets/fonts/museo/MuseoModerno-Thin.ttf
          weight: 100
        - asset: assets/fonts/museo/MuseoModerno-Regular.ttf
          weight: 400
        - asset: assets/fonts/museo/MuseoModerno-Bold.ttf
          weight: 700
